### ISSUE TITLE
파일 정리

### ISSUE THREAD

**Issue by PCHANUL** [team-pakchoi/msh#116]
- 폴더
- static
- 함수 이름

**Comment by srngch** [comment]
- `util` 디렉토리 기준: 여러 함수에서 반복적으로 사용하는 함수들

**Comment by PCHANUL** [comment]
- command, parse 관련 함수를 `util` 파일로 정리
- `exec_` 이름 제거 후 `exec` 폴더로 이동
- `util` 폴더 안 파일 이름에서 `util_` 제거

**Comment by srngch** [comment]
사용하지 않는 libft 함수 파일 지우기
