### ISSUE TITLE
`$` 파싱 처리

### ISSUE THREAD

**Issue by srngch** [team-pakchoi/msh#135]
```bash
echo "$=TEST"
// bash
$=TEST
// minishell
=TEST
```

`"`로 감싼 문자열 그대로 출력

-> `$` 뒤의 문자가 영문대소문자, 숫자, `_`가 아닌 경우 변수 파싱 하지 않음

_Originally posted by @srngch in https://github.com/42pakchoi/minishell/issues/130#issuecomment-1115749676_

**Comment by PCHANUL** [comment]
#107 에서 해결
